---
Organizations:
  - &distributor-example-com
      Name: distributor-example-com
      ID: distributor-example-com
      MSPDir: keyfiles/peerOrganizations/distributor.example.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('distributor-example-com.admin', 'distributor-example-com.peer', 'distributor-example-com.client')"
        Writers:
          Type: Signature
          Rule: "OR('distributor-example-com.admin', 'distributor-example-com.client')"
        Admins:
          Type: Signature
          Rule: "OR('distributor-example-com.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('distributor-example-com.peer')"

      AnchorPeers:
      - Host: 192.168.0.103
        Port: 7014
      - Host: 192.168.0.103
        Port: 7015
  - &example-com
      Name: example-com
      ID: example-com
      MSPDir: keyfiles/ordererOrganizations/example.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('example-com.member')"
        Writers:
          Type: Signature
          Rule: "OR('example-com.member')"
        Admins:
          Type: Signature
          Rule: "OR('example-com.admin')"
  - &farmer-example-com
      Name: farmer-example-com
      ID: farmer-example-com
      MSPDir: keyfiles/peerOrganizations/farmer.example.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('farmer-example-com.admin', 'farmer-example-com.peer', 'farmer-example-com.client')"
        Writers:
          Type: Signature
          Rule: "OR('farmer-example-com.admin', 'farmer-example-com.client')"
        Admins:
          Type: Signature
          Rule: "OR('farmer-example-com.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('farmer-example-com.peer')"

      AnchorPeers:
      - Host: 192.168.0.103
        Port: 7010
      - Host: 192.168.0.103
        Port: 7011
  - &retailer-example-com
      Name: retailer-example-com
      ID: retailer-example-com
      MSPDir: keyfiles/peerOrganizations/retailer.example.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('retailer-example-com.admin', 'retailer-example-com.peer', 'retailer-example-com.client')"
        Writers:
          Type: Signature
          Rule: "OR('retailer-example-com.admin', 'retailer-example-com.client')"
        Admins:
          Type: Signature
          Rule: "OR('retailer-example-com.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('retailer-example-com.peer')"

      AnchorPeers:
      - Host: 192.168.0.103
        Port: 7016
      - Host: 192.168.0.103
        Port: 7017
  - &transporter-example-com
      Name: transporter-example-com
      ID: transporter-example-com
      MSPDir: keyfiles/peerOrganizations/transporter.example.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('transporter-example-com.admin', 'transporter-example-com.peer', 'transporter-example-com.client')"
        Writers:
          Type: Signature
          Rule: "OR('transporter-example-com.admin', 'transporter-example-com.client')"
        Admins:
          Type: Signature
          Rule: "OR('transporter-example-com.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('transporter-example-com.peer')"

      AnchorPeers:
      - Host: 192.168.0.103
        Port: 7018
      - Host: 192.168.0.103
        Port: 7019
  - &wholesaler-example-com
      Name: wholesaler-example-com
      ID: wholesaler-example-com
      MSPDir: keyfiles/peerOrganizations/wholesaler.example.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('wholesaler-example-com.admin', 'wholesaler-example-com.peer', 'wholesaler-example-com.client')"
        Writers:
          Type: Signature
          Rule: "OR('wholesaler-example-com.admin', 'wholesaler-example-com.client')"
        Admins:
          Type: Signature
          Rule: "OR('wholesaler-example-com.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('wholesaler-example-com.peer')"

      AnchorPeers:
      - Host: 192.168.0.103
        Port: 7012
      - Host: 192.168.0.103
        Port: 7013

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft

  BatchTimeout: 2s

  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  Addresses:
  - 192.168.0.103:7030
  EtcdRaft:
    Consenters:
    - Host: 192.168.0.103
      Port: 7030
      ClientTLSCert: keyfiles/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
      ServerTLSCert: keyfiles/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  OrgChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - *distributor-example-com
      - *farmer-example-com
      - *retailer-example-com
      - *transporter-example-com
      - *wholesaler-example-com
      Capabilities:
        <<: *ApplicationCapabilities

  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *example-com
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - <<: *example-com
    Consortiums:
      SampleConsortium:
        Organizations:
        - *distributor-example-com
        - *farmer-example-com
        - *retailer-example-com
        - *transporter-example-com
        - *wholesaler-example-com
